[workspace]
authors = ["klimantas <kevin.limanta.th@dartmouth.edu>"]
channels = ["conda-forge"]
name = "pcn"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = "3.12.*"
uv = ">=0.9.30,<0.10"
numpy = ">=2.4.2,<3"
networkx = ">=3.6.1,<4"
pytorch = "2.8.*"

[pypi-dependencies]
torch-geometric = ">=2.7.0, <3"

[target.linux-64.tasks]
post-install = "uv pip install --no-build-isolation torch-scatter torch-sparse torch-cluster torch-spline-conv pyg_lib -f https://data.pyg.org/whl/torch-2.8.0+cpu.html"

